### PR TITLE
tafkars: add LICENSE

### LINKED ISSUE #8: Missing LICENSE
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

### PR DESCRIPTION
**Pull request by jeremyhager**
Resolves #8 

Note: Lemmy also uses GPLv3, while using MIT and Apache licensed packages such as serde: https://github.com/LemmyNet/lemmy/blob/main/LICENSE

Let me know if you'd prefer a different version etc.

### CODE REVIEW

**Comment by derivator** [comment]
How about MIT for `tafkars` and AGPL for `tafkars-lemmy`? Also has to be set in their respective `Cargo.toml` files. And I would prefer to get rid of that superfluous merge commit. Thanks! :)

**Comment by jeremyhager** [comment]
Moving this to a draft for now, apologies. I'll update soon

**Comment by jeremyhager** [comment]
@derivator sorry this took longer, let me know what you think of this.

Admittedly I am a little confused on if you mean tafkars crate vs. tafkars project, so what I did was set the workspace license to AGPL, which tafkars-lemmy inherits, and then specifically use MIT for the tafkars crate. I updated the cargo files to include descriptors etc. from the workspace root, expect in the tafkars crate where it uses MIT.

I believe I need to use my own name in the MIT license as well, since I helped contribute to that crate. Thus, my name has been added in.

**Comment by derivator** [comment]
Looking good! Didn't even know about `[workspace.package]`, that's useful. Probably should add the [`roux` author ](https://github.com/halcyonnouveau/roux/blob/master/LICENSE)to the MIT license as well?

**Comment by jeremyhager** [comment]
Good call, just added and did a little cleanup with the toml files.

**Comment by derivator** [comment]
Big thanks!

**Pull request merged**
